In [73]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
# create list
person_height = [5.2, 5.4, 4.4, 4.5, 5.6, 6]
person_weight = [81, 55, 65, 70, 45, 44]

# create arrays
person_height = np.array(person_height)
person_weight = np.array(person_weight)


In [3]:
person_height

array([5.2, 5.4, 4.4, 4.5, 5.6, 6. ])

In [4]:
person_weight

array([81, 55, 65, 70, 45, 44])

In [5]:
print(type(person_weight))

<class 'numpy.ndarray'>


In [6]:
my_array = np.array([11, 22, 33, 24, 57, 473])
print(my_array)

[ 11  22  33  24  57 473]


In [8]:
#indexing
#get 1st element
#indexing starts from '0'
print(my_array[0])

#get 3rd element
print(my_array[2])

11
33


In [9]:
#indexing in 2 dimensions, list of lists, array or arrays
my_array =np.array([[101, 231, 321], 
                    [412, 512, 622], 
                    [712, 812, 912]])
my_array

array([[101, 231, 321],
       [412, 512, 622],
       [712, 812, 912]])

In [11]:
#Retrieve an element of the 2D array using two indices i and j.  
#i selects the row, and j selects the column:
#get the element in the 3rd row and 2nd column
print(my_array[2,1])

812


In [12]:
# same request as above, but use brackets
print(my_array[2][1])

812


In [13]:
#pick a row or column
print(my_array[2])

[712 812 912]


In [15]:
#pick a row or column
print(my_array[:,2])

[321 622 912]


In [17]:
#slicing a 1D array
my_array =[101, 121, 112, 123, 114]

In [19]:
#pick 2nd, 3rd, and 4th element
new_array = my_array[1:4]
new_array

[121, 112, 123]

In [20]:
#slice notation specifies a start and an end value [start:end], 
#where 'start' is inclusive, but 'end'is exclusive.

#first 3 elements 
c= my_array[:3]
c

[101, 121, 112]

In [21]:
# all elements from 112
d = my_array[2:]
d

[112, 123, 114]

In [23]:
# get complete array
e = my_array[:]
e

[101, 121, 112, 123, 114]

In [24]:
#slicing 2D array (matrix)
my_array = np.array([[101, 131, 122, 113, 143], 
                     [145, 165, 137, 318, 193], 
                     [240, 241, 252, 253, 324],
                     [225, 126, 727, 928, 129]])

my_array

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [25]:
#select all rows except 1st
#select 3rd and 4th column
print(my_array[1:,2:4])

[[137 318]
 [252 253]
 [727 928]]


In [ ]:
# The index returns an element of the array, 
# the slice returns a list of elements

In [ ]:
#operations of an array

In [26]:
my_array1 = np.array([120, 230, 310, 410, 150])
my_array2 = np.arange(5)

In [27]:
#add the 2 arrays
my_array3 = my_array1 + my_array2
my_array3

array([120, 231, 312, 413, 154])

In [28]:
#WTF how...this is how
my_array1

array([120, 230, 310, 410, 150])

In [29]:
#continued
my_array2

array([0, 1, 2, 3, 4])

In [ ]:
#continued
#np.arange(5)
#was a function to great an array with a range of 5 starting from '0'
#so  this was the result array([0, 1, 2, 3, 4])
# and when you add the 2 arrays together
#   [120, 230, 310, 410, 150]
#  +[0, 1, 2, 3, 4]
# = 121, 231, 312, 413, 154

In [30]:
my_array4 = np.array([1,2,3,5])
my_array1 + my_array4

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [31]:
my_array1

array([120, 230, 310, 410, 150])

In [32]:
my_array4

array([1, 2, 3, 5])

In [ ]:
# can't add same dimension, 1D, 
#but do not have the same number of elements.

In [33]:
# multiply each element in the array by 4
my_array*4

array([[ 404,  524,  488,  452,  572],
       [ 580,  660,  548, 1272,  772],
       [ 960,  964, 1008, 1012, 1296],
       [ 900,  504, 2908, 3712,  516]])

In [34]:
my_array

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [35]:
#square, cube, etc of each element in array
my_array**4

array([[   104060401,    294499921,    221533456,    163047361,
           418161601],
       [   442050625,    741200625,    352275361,  10226063376,
          1387488001],
       [  3317760000,   3373402561,   4032758016,   4097152081,
         11019960576],
       [  2562890625,    252047376, 279342903841, 741637881856,
           276922881]])

In [38]:
# use numpy with comparison expressions
my_array = np.array([34, 45, 67, 45, 23])

# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

array([False,  True,  True,  True, False])

In [39]:
#pass the above boolean array to the main array to fetch the values 
#that satisfy the comparison conditionmy_array[new_array]

#elements greater than or equal to 40
my_array[new_array]

array([45, 67, 45])

In [40]:
my_array

array([34, 45, 67, 45, 23])

In [42]:
# rather than creating a separate array of booleans, 
#you can specify the comparison operation directly on the main array
my_array[my_array >=40]

array([45, 67, 45])

In [43]:
#arithmetic functions in numpy
my_array = np.array([5,7,8,2,4])
my_array

array([5, 7, 8, 2, 4])

In [44]:
#sum() function adds all the values in the array and gives a scalar output
#add all the elements
#calling the sum() method from my_array CLASS
my_array.sum()

26

In [47]:
# alternative taking np sum()function and apply it to my_array
np.sum(my_array)

26

In [45]:
#min() function finds the lowest value in the array
my_array.min()

2

In [48]:
#alternate min()
np.min(my_array)

2

In [46]:
#power() function raises the numbers in the array to the given value'
# get the cube of the elements
np.power(my_array, 3)

array([125, 343, 512,   8,  64])

In [50]:
my_array**3

array([125, 343, 512,   8,  64])

In [52]:
#concatenation of array- arrays cab be concatenated only if they 
# have the same shape, except in the dimension corresponding to 
#the axis of concatenation

#concate two 1D array
array_x = np.array([11, 22, 13])
array_y = np.array([23, 22, 12])
np.concatenate([array_x, array_y])

array([11, 22, 13, 23, 22, 12])

In [53]:
# concat more than 2 arrays at once
array_z = np.array([23, 45])
print(np.concatenate([array_x, array_y, array_z]))

[11 22 13 23 22 12 23 45]


In [55]:
#concatenate 2D array
my_array = np.array([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
#concatenate along first axis
#by default concatenate() is along 'axis = 0'
# axis 0 is rows
np.concatenate([my_array,my_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
#concatenate along the second axis
# axis 1 is the columns
np.concatenate([my_array, my_array], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#nb- you can not concatenate arrays with different dimensions

In [ ]:
#splitting of array is the inverse of concatenate
#splitting splits the array into multiple sub_arrays.  
# split is implemented by functions split(), hsplit()

In [58]:
#split() the array unto sub-arrays
array_x = np.arange(8)
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [60]:
#split the 1D array at positions indicated, at 5th and 7 indices
array_y=np.split(array_x,[5,7])
print(array_y)

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


In [61]:
#split 'array_x' into 3 sub-arrays
np.split(array_x, 3)

ValueError: array split does not result in an equal division

In [ ]:
#error due to the # of dimensions needs to be evenly split 
#(arrays need to be equally sized)

In [63]:
array_zz = np.arange(9)
array_zz

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
np.split(array_zz, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [65]:
#alternative
#split 'array_x' into 3 sub-arrays
# the split will not be equal
#split "array_x" into 3 sub-arrays using 'array_split'
np.array_split(array_z, 3)

[array([23]), array([45]), array([], dtype=int64)]

In [ ]:
#above didn't have 3 elements, so the last was an empty array!

In [66]:
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [67]:
#vsplit() function is used to split an array into multiple sub arrays vertically (row-wise)
#v=rows
my_array = np.arange(20.0).reshape(4,5)
my_array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [ ]:
#above explanation
#reshape (4, 5) = 4 rows and 5 columns

In [68]:
np.vsplit(my_array, 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

In [71]:
#hsplit is used to split an array into multiple sub_arrays 
#horizontally (column-wise)
my_array = np.arange(16.0).reshape(4,4)
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [72]:
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [ ]:
#Data Structures
#Pandas has 2 data structures as follows:
    #1. A Series is 1-dimensional labeled array and holds data of any type
    #(integer, string, boolean, float, python objects)
    # its axis labels are collectively called and index
    #2. DataFrame is a 2-dimensional labeled data structure with columns.
    

In [ ]:
#Panda Series
# Intro to Panda Series and  Creating Series
#pandas Series is a one-dimensial labeled array capable of holding any 
#type of data
#Series a sequence of homegeneous data types similar to array, list, or
#column in a table.
# it will  assign a labeled index to each item in a series.  
#By default, each item will receive an index label from 0 to N, 
#where N is the length of the Series minus 1.

In [76]:
#create a numeric series
#note that the range does not have np. or pd. range...
# it is python builtin function
index position and element value
numbers = range(1,100, 5)
#length of the series-1
pd.Series(numbers)
# in python, the row names are called index

0      1
1      6
2     11
3     16
4     21
5     26
6     31
7     36
8     41
9     46
10    51
11    56
12    61
13    66
14    71
15    76
16    81
17    86
18    91
19    96
dtype: int64

In [77]:
#create an object series
string = 'hi', 'how', 'are', 'you','?'
pd.Series(string)

0     hi
1    how
2    are
3    you
4      ?
dtype: object

In [78]:
#create a Series with both numeric and string values
# numeric values treated as object
s= pd.Series([345, 'London', 34.5, -34.45, 'Happy Birthday'])
s

0               345
1            London
2              34.5
3            -34.45
4    Happy Birthday
dtype: object

In [79]:
#set index values fro a Series
marks = [60, 89, 74, 86]
subject = ['maths', 'science', 'english', 'social science']

pd.Series(marks, index = subject)

maths             60
science           89
english           74
social science    86
dtype: int64

In [81]:
#create a Series from a dictionary
# on passing a dict, the index in the resulting Series will have 
#the dict's keys in sorted order
data = {'maths':60, 'science':89, 'english':76, 'social science': 86}

pd.Series(data)

maths             60
science           89
english           76
social science    86
dtype: int64

In [84]:
#Series with missing values
#if we pass a key that us not defined then its value will be NAN
subject = ['maths', 'science', 'art and craft', 'social science']
marks_series =pd.Series(data, index = subject)
print(marks_series)

maths             60.0
science           89.0
art and craft      NaN
social science    86.0
dtype: float64


In [85]:
#manipulating Series
# to check for null values using .isnull
# False indicates that the value is not null
marks_series.isnull()

maths             False
science           False
art and craft      True
social science    False
dtype: bool

In [86]:
#check for null values
#True indicates that the value is not null
marks_series.notnull()

maths              True
science            True
art and craft     False
social science     True
dtype: bool

In [88]:
#to know the subjects in which marks score is more than 75
# think like this "in marks_series where marks_series is greater than 75"
# this will list only list actual values greater than 75
marks_series[marks_series > 75]

science           89.0
social science    86.0
dtype: float64

In [87]:
# this will go through the Series and give you a boolean for each element
marks_series>75

maths             False
science            True
art and craft     False
social science     True
dtype: bool

In [89]:
# assign 68 marks to 'art and craft'
marks_series['art and craft'] = 68
marks_series

maths             60.0
science           89.0
art and craft     68.0
social science    86.0
dtype: float64

In [91]:
marks_series['science'] = 98
marks_series

maths             60.0
science           98.0
art and craft     68.0
social science    86.0
dtype: float64

In [92]:
# check whether maths is equal to 73
marks_series['maths']==73

False

In [93]:
#alternative
marks_series.maths ==73

False

In [95]:
#sorting a numeric sequence
values = pd.Series ([23, 45, np.nan, 41, 23, 34, 55, np.nan, 34, 20])
values

0    23.0
1    45.0
2     NaN
3    41.0
4    23.0
5    34.0
6    55.0
7     NaN
8    34.0
9    20.0
dtype: float64

In [96]:
#ascending order
values.sort_values(ascending = True)

9    20.0
0    23.0
4    23.0
5    34.0
8    34.0
3    41.0
1    45.0
6    55.0
2     NaN
7     NaN
dtype: float64

In [97]:
#descending order
values.sort_values(ascending = False)

6    55.0
1    45.0
3    41.0
5    34.0
8    34.0
0    23.0
4    23.0
9    20.0
2     NaN
7     NaN
dtype: float64

In [98]:
#sorting a categorical series
string_values = pd.Series(['a', 'j', 'd', 'f', 't', 'a'])
string_values

0    a
1    j
2    d
3    f
4    t
5    a
dtype: object

In [99]:
#ascending order
string_values.sort_values(ascending=True)

0    a
5    a
2    d
3    f
1    j
4    t
dtype: object

In [100]:
#descending order
string_values.sort_values(ascending=False)

4    t
1    j
3    f
2    d
0    a
5    a
dtype: object

In [102]:
#rank a Series
#recall the marks_series
marks_series.rank(ascending=True, pct=False)

maths             1.0
science           4.0
art and craft     2.0
social science    3.0
dtype: float64

In [ ]:
#Pandas DataFrames
#intro to df and creating df
# A DF is a tabular representtion of data containing an ordered 
#collection of columns, each of which can be a different type 
#(numeric, string, boolean, and so on)
#The DF has a row and column index; it can be thought of as a dict of 
#Series
#all sharing the same index.  In a DF, the dtat is stored as one or more
#2-dimensional blocks rather than a list, dict, or some other collection
#of 1-dimensional arrays
#while a dataframe is physically 2-dimensional, it can be used to 
#represent  higher dimensional data in a tabular format using hierarchical
#indexing

In [104]:
#creating a data frame from a dictionary
data = {'subject': ['maths', 'history', 'science', 'english', 'geograpy', 'art'], 
        'marks': (45, 65, 78, 65, 80, 78),
        'cgpa': [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]}

df = pd.DataFrame(data)
print(df)

    subject  marks  cgpa
0     maths     45   2.5
1   history     65   3.0
2   science     78   3.5
3   english     65   2.0
4  geograpy     80   4.0
5       art     78   4.0


In [ ]:
# ABOVE the resulting df is index automatically, 'marks' are in a tuple

In [111]:
# to create a df from a series
subject = pd.Series(['maths', 
                      'history', 
                      'science', 
                      'english', 
                      'geograpy', 
                      'art'])
marks = pd.Series([45, 65, 78, 65, 80, 78])
cgpa = pd.Series([2.5, 3.0, 3.5, 2.0, 4.0, 4.0])

In [112]:
pd.DataFrame([subject, marks, cgpa], index = ['subject', 'marks', 'cgpa'])

0        1        2        3         4    5
subject  maths  history  science  english  geograpy  art
marks       45       65       78       65        80   78
cgpa       2.5      3.0      3.5      2.0       4.0  4.0

In [113]:
#change to a vertical df use.T for transpose
pd.DataFrame([subject, marks, cgpa], index = ['subject', 'marks', 'cgpa']).T

subject marks cgpa
0     maths    45  2.5
1   history    65  3.0
2   science    78  3.5
3   english    65  2.0
4  geograpy    80  4.0
5       art    78  4.0

In [114]:
#create df from lists
subject = ['maths','history','science','english','geograpy','art']
marks = [45, 65, 78, 65, 80, 78]
cgpa = [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]

In [115]:
pd.DataFrame([subject, marks, cgpa], index = ['subject', 'marks', 'cgpa']).T

subject marks cgpa
0     maths    45  2.5
1   history    65  3.0
2   science    78  3.5
3   english    65  2.0
4  geograpy    80  4.0
5       art    78  4.0